### ISSUE TITLE
Proposal Review

### ISSUE THREAD

**Issue by ragegage** [CassBaltz/ot-capstone-project#1]
Good start to the proposal. There are a few things I'd like you to clean up:
- [x] Add wireframe images to your wireframes page (https://github.com/CassBaltz/ot-capstone-project/blob/master/docs/views.md)
- [x] Fix up the React components page so that your routes match your list of bolded components (https://github.com/CassBaltz/ot-capstone-project/blob/master/docs/components.md)
- [x] Touch up your API endpoints page - I don't think you have a "Notebook" model and some of your models are missing (https://github.com/CassBaltz/ot-capstone-project/blob/master/docs/flux-cycles.md)
- [x] Update your API endpoints page so that all routing happens on the frontend (incl. login & signup)
- [x] In your schema, is the reviews table supposed to hold the content of the review? (https://github.com/CassBaltz/ot-capstone-project/blob/master/docs/schema.md)
- [x] I think you should budget in some time to style your login/signup pages after you complete your frontend auth, and also add more granular steps to the later pieces of the timeline.
- [x] I'd like you to add Creating restaurants as a bonus feature.

**Comment by CassBaltz** [comment]
I think everything has been updated, although I would not be surprised if there is stuff missing still. I also may want to rework a little of the layout after the lecture in class this morning. Thanks for the pointers.

**Comment by ragegage** [comment]
Feel free to close this issue if it's all done :)
